@url = http://localhost:5107/api/Personas

### Listar personas
GET {{url}}

### Crear persona con nombres opcionales omitidos
POST {{url}}
Content-Type: application/json

{"primerNombre":"Ana","primerApellido":"Pérez","dui":"01234567-8","fechaNacimiento":"2000-02-29"}

### Consultar el Id devuelto al crear
GET {{url}}/1

### Actualizar
PUT {{url}}/1
Content-Type: application/json

{"id":1,"primerNombre":"Ana","segundoNombre":"María","primerApellido":"Pérez","segundoApellido":"López","dui":"01234567-8","fechaNacimiento":"2000-02-29"}

### Fecha imposible: debe devolver 400
POST {{url}}
Content-Type: application/json

{"primerNombre":"Ana","primerApellido":"Pérez","dui":"01234567-8","fechaNacimiento":"2000-02-30"}

### DUI inválido: debe devolver 400
POST {{url}}
Content-Type: application/json

{"primerNombre":"Ana","primerApellido":"Pérez","dui":"123","fechaNacimiento":"2000-02-29"}

### Eliminar
DELETE {{url}}/1
